### ISSUE TITLE
Build is failed

### ISSUE THREAD

**Issue by knalbandianbrightgrove** [mateusmaso/underscore.deepclone#5]
Please update build files

**Comment by mateusmaso** [comment]
Hey, could you be more specific? If you are experiencing any errors let me know

**Comment by knalbandianbrightgrove** [comment]
@mateusmaso 

Yes, you updated this https://github.com/mateusmaso/underscore.deepclone/blob/master/src/underscore.deepclone.js

but you didn't update this
https://github.com/mateusmaso/underscore.deepclone/blob/master/dist/underscore.deepclone.js

**Comment by mateusmaso** [comment]
Wow, how did I miss that? My bad, I just released a new version fixing it. Thanks man!
